# Generated by Django 5.0.1 on 2025-08-13 17:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_count', models.IntegerField(default=0)),
                ('total_size', models.BigIntegerField(default=0)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_data', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='documents.documentsession')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('document_type', models.CharField(choices=[('pdf', 'PDF Document'), ('xlsx', 'Excel Spreadsheet'), ('docx', 'Word Document')], max_length=10)),
                ('file_size', models.BigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending Processing'), ('processing', 'Processing'), ('ready', 'Ready'), ('error', 'Error')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.documentsession')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='documentsession',
            index=models.Index(fields=['created_at'], name='documents_d_created_f30d6d_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['session', 'status'], name='documents_d_session_78c1f6_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['uploaded_at'], name='documents_d_uploade_65506e_idx'),
        ),
    ]
