# Generated by Django 5.0.1 on 2025-08-15 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_conversation_is_active_conversation_title_and_more'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='document',
            name='documents_d_session_78c1f6_idx',
        ),
        migrations.RemoveField(
            model_name='document',
            name='session',
        ),
        migrations.RemoveField(
            model_name='documentcontext',
            name='session',
        ),
        migrations.AddField(
            model_name='document',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='chat.conversation'),
        ),
        migrations.AddField(
            model_name='documentcontext',
            name='conversation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.conversation'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['conversation', 'status'], name='documents_d_convers_cc70df_idx'),
        ),
    ]
