# Generated by Django 5.0.1 on 2025-08-15 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='preview_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
