# Generated by Django 5.0.1 on 2025-08-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_add_preview_html_to_artifact'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(default='New Conversation', max_length=200),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['session', 'is_active'], name='chat_conver_session_9e237d_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['last_activity'], name='chat_conver_last_ac_ab750d_idx'),
        ),
    ]
